// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package datastructures

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User_Status int32

const (
	User_ACTIVE  User_Status = 0
	User_DELETED User_Status = 100
)

var User_Status_name = map[int32]string{
	0:   "ACTIVE",
	100: "DELETED",
}

var User_Status_value = map[string]int32{
	"ACTIVE":  0,
	"DELETED": 100,
}

func (x User_Status) String() string {
	return proto.EnumName(User_Status_name, int32(x))
}

func (User_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0, 0}
}

// [START messages]
type User struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Created              *timestamp.Timestamp `protobuf:"bytes,2,opt,name=created,proto3" json:"created,omitempty"`
	LastUpdated          *timestamp.Timestamp `protobuf:"bytes,3,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	Password             string               `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	Vrn                  string               `protobuf:"bytes,5,opt,name=vrn,proto3" json:"vrn,omitempty"`
	AccessToken          string               `protobuf:"bytes,6,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken         string               `protobuf:"bytes,7,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	TokenExpiry          string               `protobuf:"bytes,8,opt,name=token_expiry,json=tokenExpiry,proto3" json:"token_expiry,omitempty"`
	TokenType            string               `protobuf:"bytes,9,opt,name=token_type,json=tokenType,proto3" json:"token_type,omitempty"`
	Email                string               `protobuf:"bytes,10,opt,name=email,proto3" json:"email,omitempty"`
	Status               User_Status          `protobuf:"varint,11,opt,name=status,proto3,enum=datastructures.User_Status" json:"status,omitempty"`
	VatFlatRate          string               `protobuf:"bytes,12,opt,name=vat_flat_rate,json=vatFlatRate,proto3" json:"vat_flat_rate,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetCreated() *timestamp.Timestamp {
	if m != nil {
		return m.Created
	}
	return nil
}

func (m *User) GetLastUpdated() *timestamp.Timestamp {
	if m != nil {
		return m.LastUpdated
	}
	return nil
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *User) GetVrn() string {
	if m != nil {
		return m.Vrn
	}
	return ""
}

func (m *User) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *User) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

func (m *User) GetTokenExpiry() string {
	if m != nil {
		return m.TokenExpiry
	}
	return ""
}

func (m *User) GetTokenType() string {
	if m != nil {
		return m.TokenType
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetStatus() User_Status {
	if m != nil {
		return m.Status
	}
	return User_ACTIVE
}

func (m *User) GetVatFlatRate() string {
	if m != nil {
		return m.VatFlatRate
	}
	return ""
}

func init() {
	proto.RegisterEnum("datastructures.User_Status", User_Status_name, User_Status_value)
	proto.RegisterType((*User)(nil), "datastructures.User")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 356 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x91, 0x4f, 0x6f, 0xda, 0x40,
	0x10, 0xc5, 0x6b, 0xfe, 0x18, 0x18, 0x1b, 0x84, 0x56, 0x3d, 0xac, 0xa8, 0xaa, 0x02, 0xbd, 0x70,
	0x32, 0x12, 0xf4, 0xda, 0x43, 0x55, 0x5c, 0xa9, 0x52, 0x4e, 0x8e, 0xc9, 0xd5, 0x1a, 0xec, 0x81,
	0x58, 0x31, 0xd8, 0xda, 0x1d, 0x93, 0xf0, 0x41, 0xf3, 0x7d, 0x22, 0xef, 0x42, 0xa4, 0x9c, 0x72,
	0xdb, 0x79, 0xef, 0xf7, 0x9e, 0x46, 0xb3, 0x00, 0xb5, 0x26, 0x15, 0x54, 0xaa, 0xe4, 0x52, 0x8c,
	0x32, 0x64, 0xd4, 0xac, 0xea, 0x94, 0x6b, 0x45, 0x7a, 0xf2, 0xe3, 0x50, 0x96, 0x87, 0x82, 0x96,
	0xc6, 0xdd, 0xd5, 0xfb, 0x25, 0xe7, 0x47, 0xd2, 0x8c, 0xc7, 0xca, 0x06, 0xe6, 0xaf, 0x6d, 0xe8,
	0x6c, 0x35, 0x29, 0x31, 0x82, 0x56, 0x9e, 0x49, 0x67, 0xea, 0x2c, 0x06, 0x51, 0x2b, 0xcf, 0xc4,
	0x2f, 0xe8, 0xa5, 0x8a, 0x90, 0x29, 0x93, 0xad, 0xa9, 0xb3, 0xf0, 0x56, 0x93, 0xc0, 0x76, 0x05,
	0xb7, 0xae, 0x20, 0xbe, 0x75, 0x45, 0x37, 0x54, 0xfc, 0x06, 0xbf, 0x40, 0xcd, 0x49, 0x5d, 0x65,
	0x26, 0xda, 0xfe, 0x34, 0xea, 0x35, 0xfc, 0xd6, 0xe2, 0x62, 0x02, 0xfd, 0x0a, 0xb5, 0x7e, 0x2e,
	0x55, 0x26, 0x3b, 0x66, 0x95, 0xf7, 0x59, 0x8c, 0xa1, 0x7d, 0x56, 0x27, 0xd9, 0x35, 0x72, 0xf3,
	0x14, 0x33, 0xf0, 0x31, 0x4d, 0x49, 0xeb, 0x84, 0xcb, 0x27, 0x3a, 0x49, 0xd7, 0x58, 0x9e, 0xd5,
	0xe2, 0x46, 0x12, 0x3f, 0x61, 0xa8, 0x68, 0xaf, 0x48, 0x3f, 0x5e, 0x99, 0x9e, 0x61, 0xfc, 0xab,
	0x68, 0xa1, 0x19, 0xf8, 0xc6, 0x4c, 0xe8, 0xa5, 0xca, 0xd5, 0x45, 0xf6, 0x6d, 0x8f, 0xd1, 0x42,
	0x23, 0x89, 0xef, 0x00, 0x16, 0xe1, 0x4b, 0x45, 0x72, 0x60, 0x80, 0x81, 0x51, 0xe2, 0x4b, 0x45,
	0xe2, 0x2b, 0x74, 0xe9, 0x88, 0x79, 0x21, 0xc1, 0x38, 0x76, 0x10, 0x6b, 0x70, 0x35, 0x23, 0xd7,
	0x5a, 0x7a, 0x53, 0x67, 0x31, 0x5a, 0x7d, 0x0b, 0x3e, 0xfe, 0x4e, 0xd0, 0x1c, 0x3e, 0xb8, 0x37,
	0x48, 0x74, 0x45, 0xc5, 0x1c, 0x86, 0x67, 0xe4, 0x64, 0x5f, 0x20, 0x27, 0x0a, 0x99, 0xa4, 0x6f,
	0xb7, 0x39, 0x23, 0xff, 0x2b, 0x90, 0x23, 0x64, 0x9a, 0xcf, 0xc0, 0xb5, 0x29, 0x01, 0xe0, 0xfe,
	0xf9, 0x1b, 0xff, 0x7f, 0x08, 0xc7, 0x5f, 0x84, 0x07, 0xbd, 0x4d, 0x78, 0x17, 0xc6, 0xe1, 0x66,
	0x9c, 0xed, 0x5c, 0x73, 0xea, 0xf5, 0x5b, 0x00, 0x00, 0x00, 0xff, 0xff, 0x75, 0x96, 0x45, 0xdf,
	0x1d, 0x02, 0x00, 0x00,
}
